### ISSUE TITLE
Need more events from mesh-lite OTA (AEGHB-886)

### ISSUE THREAD

**Issue by ruslanslobozhenuk** [espressif/esp-mesh-lite#130]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate.
- [X] Described the feature in detail and justified the reason for the request.
- [X] Provided specific use cases and examples.

### Feature description

I have next situation:

W (35849) [ESP_Mesh_Lite_OTA]: OTA Image version for Project: 1.0.1_213745f. Expected: 1.0.1_213745f
W (35859) [ESP_Mesh_Lite_OTA]: Current running version is same as the new. We will not continue the update.
E (35869) [ESP_Mesh_Lite_OTA]: image header verification failed

I dont have any event from core!
P.S. After repeat OTA, I have message:

E (548739) mesh_lite_ota: OTA already in progress. Please try later.

### Use cases

Mesh-lite OTA diagnostic state.

**Comment by tswen** [comment]
The print you sent was when esp_mesh_lite_transmit_file_start just entered. Because it was determined that the firmware you want to upgrade is the same as the current firmware version, the upgrade was not performed. You just need to check the return value of esp_mesh_lite_transmit_file_start. No event is required.
